title: Felix Moerman's homepage
description: Welcome to my website. You can explore to find more info about me, my career, and my hobbies.
timezone: Europe/Zurich
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: femoerman/feeling-responsive